### PR TITLE
:TSSearch command & FZF integration

### PR DESCRIPTION
**Pull request by pyrho**
This PR introduces the `:TSSearch <query>` command which allows to search for symbols throughout the project.
When called, it will populate a location window with the results.

The same python client function is also used to have an [FZF](https://github.com/junegunn/fzf.vim) (similar to denite) integration.
The integration is done via an "after/plugin" vim script which creates the `:TSSearchFZF` command if FZF is loaded, and NOOPs otherwise.

I also renamed instances of "Workplace" to "Workspace" as I think this was a typo originally.

Thanks !

### CODE REVIEW

**Comment by pyrho** [comment]
Side note, my 2 PRs on this repo are my first ever ventures into VimL territory, I'm sure there's a ton of noob-ish things in there, feel free to point out what needs improvement.

**Comment by mhartington** [comment]
I think I might hold off on this one. Currently, the client is too brittle for this, since it can't handle large data sets (which really sucks).

I need to find time to refactor the client to avoid the size limit issue.

**Comment by pyrho** [comment]
What are you referring to exactly regarding the size limit ? Is it an issue with `tsserver` itself ?
Anyway let me know how I can help.

**Comment by mhartington** [comment]
It's to do with python's subprocess. It has a pretty small buffer limit before it locks up, so doing large data requests and reads will lock it up if the data size is over a certain amount.

See 
https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/

One thought I have been having is rewriting this to use a new node-client/node-host plugin. Node's child_process is a bit easier to work with and feels a bit more natural to work with that python. 

Another thought I had was re-writing the python client, but have not had a whole lot of time for this

**Comment by pyrho** [comment]
Thank you for the details.

I will look into [neovim/node-client](https://github.com/neovim/node-client) and see if I can come up with something :)

**Comment by pyrho** [comment]
While [https://github.com/neovim/node-host](https://github.com/neovim/node-host) looks promising (and I'm also more fluent in nodeJS than python), migrating the client to Node means we won't be able to use the client for the [deoplete](https://github.com/Shougo/deoplete.nvim) completion source..

You could create a vim function from the NodeJS plugin, and later call that vim function from the deoplete source but the deoplete docs state:
> Note: If you call Vim functions in your source, it is not asynchronous.

Which totally defeats the purpose.

So I think we should stick with python for the client, if we want to provide a deoplete source.

**Comment by mhartington** [comment]
I think I can do a bit of magic to make it work 😉

**Comment by pyrho** [comment]
Care to elaborate what your idea is ?
I'm willing to (help you)? work on an implementation of the client in (type|java)script.

**Comment by pyrho** [comment]
`tsserver` accepts a `maxResultCount` (see [here](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L2084).

Maybe this should be enough for now in making sure the process doesn't hang due to python's subprocess module limitations ?

Tell me if that's good enough for this PR and I'll update it.

**Comment by mhartington** [comment]
So tested this and had some issues with it. Im hoping to make it so it constantly provides feedback, similar to how FZF's `Ag` command works.

**Comment by pyrho** [comment]
What kind of feedback are you expecting ? An empty FZF window ? That's how my FZF/Ag works.
Is that the only issue you've encountered ?

**Comment by mhartington** [comment]
Yeah, at least at first. Then as the user starts typing it will populate the window. Kind of similar to how fzf AG command will continue running grep even as you type.

Here's what you can get with denite.
workspace

**Comment by pyrho** [comment]
Oh ok got it, that's not how I use Ag (I always input a pattern), but I agree it would be pretty cool!
We might have have bump up the `maxResultsCount` to something higher than 50 if we want this to be useful.

**Comment by pyrho** [comment]
So I think :Denite works a bit differently than FZF on this point.
With FZF you have a bunch of results when you instantiate it, and then you filter them interactively.
From what I gather of your above gif, denite repopulates the results each time you type a letter.

So for this to work like you expect it, we would need `navto` to return _all_ the workspace symbols, to be interactively filtered.

When you type `:Ag` in vim, what FZF does it basically an exhaustive list of each and every line of every files under the current working directory.

So the `:TSSearchFZF command` is meant to be used with 1 argument (i've updated the PR to enforce this)

ps: I did not succeed in getting `navto` to return all workspace symbols, it's said [here](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L1531) that `navto` accepts ".*" as a search term but it does not return any results when ".*" is provided.

**Comment by mhartington** [comment]
🎉  Looks good, thanks for working through this with me!

**Pull request merged**
