### PR TITLE
Feat diagnostics

### PR DESCRIPTION
**Pull request by mhartington**
This adds diagnostic features from TSServer.

- Runs type checking on the current file, so much faster than ale's or neomake's `tsc` checker
- Reads the projects tsconfig file
- Adds signs to the column and highlights the errors in the file
- Adds `TSGetCodeFix` which can automatically apply code fixes. Based on TSServer, so if the server does not provide a fix, we just return "no fix"

Future plan, hook into nvim buffer update API to automatically listen for changes using event emitters.  Much more reliable than vim Autocmds

### CODE REVIEW

**Comment by mhartington** [comment]
Yeah, it should. `TSImport` actually used the same logic under the hood, though with some different logic for text modifications. Eventually down the road, the TSImport will get replaced by `TSGetCodeFix.

**Comment by deltaskelta** [comment]
Cool new features, I think these really add a lot of utility to the plugin. A few issues I am having are...

- after I fix the issues, the loclist is cleared, but the gutter symbols still remain. Not sure what is going on here

- I seem to not be getting linter errors from TSLint, is this not included in the `TSGetCodeFix` command?

- the loclist seems to overwrite any other errors instead of appending to them. I am not sure if this is unchangeable loclist behavior or not. Would it be possible to make it not overwrite or optionally use qf?

- `TSGetCodeFix` shows an error when importing an svg in React

- every time I leave insert mode, all the items in the loclist disappear for a few seconds and reappear. Sometimes they just disappear and stay gone. I think this has something to do with the server crashing? Maybe that was why TSImport doesn't work sometimes until I restart vim?

**Comment by mhartington** [comment]
> after I fix the issues, the loclist is cleared, but the gutter symbols still remain. Not sure what is going on here

I've seen this too, think it's to do with the async function not awaiting to finish.

>I seem to not be getting linter errors from TSLint, is this not included in the TSGetCodeFix command?

TSLint runs in a separate process not from tsserver. Under the hood, tslint uses it's own logic to parse code. If you want to use this and tslint, try adding 

https://github.com/angelozerr/tslint-language-service

>the loclist seems to overwrite any other errors instead of appending to them. I am not sure if this is unchangeable loclist behavior or not. Would it be possible to make it not overwrite or optionally use qf?

I am doing a "clear" function to the qflist, but it does not seem to be necessary. Unfortunately you can't just do any "soft" replacements to the loclist/qflist, so a hard replace is needed.

>every time I leave insert mode, all the items in the loclist disappear for a few seconds and reappear. Sometimes they just disappear and stay gone. I think this has something to do with the server crashing? Maybe that was why TSImport doesn't work sometimes until I restart vim?

This is because the diagnostics are fire on `InsertLeave`. As for the list disappearing, I haven't seen anything, but if you want to debug a bit further, you can add 

```
let $NVIM_NODE_LOG_FILE='nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='info'
```

In your init.vim, then in your project folder, open a new terminal window and run `tail -f nvim-node.log` after the server has started to read the output. If the server crashes, it will throw an error there.

**Comment by mhartington** [comment]
> Is this always going to clash with the ALE plugin?

It might. I don't use ALE, so I'm not sure. But would gladly accept a PR if there are any conflicts.

>I would like to use prettier as an ALE Fixer because it seems to be a lot better than tslint --fix at least in my experience of it.

Again, as I don't use ALE, I don't use the fixer option.
Another option is to use neoformat as it has prettier support as well.

**Comment by deltaskelta** [comment]
I have noticed that the checking on insert leave randomly stops working and it usually happens pretty quickly. I generally have to restart vim to get it going again...

in vim when I run `:mes` I see this..

```
nvim-ts: Error: No content available.
nvim-ts: Error: No content available.
nvim-ts: Error: No content available.
nvim-ts: Error: No content available.
3 fewer lines
nvim-ts: Error: No content available.
nvim-ts: Error: No content available.
```

and in the deoplete logs I see this...

I have a very long deoplete log and I do not see anything conspicuous that looks like an error. Is there anything else I should look for?

**Comment by mhartington** [comment]
Have you tried running the log file for the node host? 

```
let $NVIM_NODE_LOG_FILE='nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='warn'

```

Then `tail -f nvim-node.log` when the server has started? 

I'm going to merge this for now and revisit the other issues in master.

**Comment by deltaskelta** [comment]
I looked at that log and I see this...

```
2018-07-09T02:26:59.761Z - info: [object Object] object
2018-07-09T02:26:59.761Z - info: Method name getCommonData
2018-07-09T02:26:59.761Z - info: getCommonData() {
        return __awaiter(this, void 0, void 0, function* () {
            let file = yield this.getCurrentFile();
            let cursorPos = yield this.getCursorPos();
            return {
                file,
                line: cursorPos[0],
                offset: cursorPos[1] + 1
            };
        });
    } function
2018-07-09T02:26:59.761Z - info: [object Object] object
2018-07-09T02:27:22.784Z - info: [nvim_typescript] coming soon...
2018-07-09T02:27:22.888Z - info: [nvim_typescript] coming soon...
```

it just kind of freezes there when it stops working.

Should I continue this here or open a new issue about it?

**Comment by mhartington** [comment]
Please open a new issue.

**Pull request merged**
