### PR TITLE
Reconfigure how project root is set

### PR DESCRIPTION
**Pull request by mhartington**
This swaps out the rather complicated search for tsconfig/jsconfig, by instead doing a simpler recursive search up directories, similar to how tern works.

- [x] rework how tsconfig is found
- [x] rework how tsserver is found. Since we're no longer able to guarantee that `node_module` is relative, we should do something different.

### CODE REVIEW

**Comment by mhartington** [comment]
@pyrho  mind testing this out locally?

**Comment by pyrho** [comment]
Hey @mhartington,

I'm having issue when I'm opening nvim from my actual project root.

I've created #63 to address the issue (and added very simple tests). And it seems to work fine on my system.
Feel free to merge all mine into yours and yours into master once you've validated my changes !

Thanks !

**Comment by tinchoz49** [comment]
@mhartington @pyrho Hey guys how are you? I've been testing the branch:

1. The fallback configuration works great.
2. I had issues with the local configuration, it seems that nvim-typescript can't find the jsconfig.json but with the `feat/rework-root-fixes-and-tests branch` it works :+1: .

Thanks for the quick solution on this!

**Comment by mhartington** [comment]
I've reworked and applied the unit tests from #63 
Merging instead

**Pull request merged**
