### PR TITLE
:TSImport command

### PR DESCRIPTION
**Pull request by pyrho**
Simple implementation for the `:TSImport` command.

This relies on `navTo` to search for import paths of the symbol under the cursor;
and also on `navTree` to check if the symbol is already imported and
where the import statement should be located in the file.

See also https://github.com/mhartington/nvim-typescript/pull/57 to make
sure python does not hang on huge projects.

References issue #56 .

### CODE REVIEW

**Comment by pyrho** [comment]
I realize you mentioned looking into [vim-import-js](https://github.com/galooshi/vim-import-js) for this. But it only applied to js. And it relied on an external globally installed npm package.

Given we pretty much already had access to the required tooling with `tsserver` and the client, I thought this way would be better.

One improvement that didn't make it in this is to augment pre-existing import statements from a given file. This implementation will create a new import statement. eg.
```
// module.ts
export interface A {...};
export interface B {...};

// anotherFile.ts
import {A} from 'module';

const b: B<CURSOR_HERE>: null;
```

Calling `:TSImport` here will add a new line just below the first one that looks like this: `import {B} from 'module'`, a better way would be to replace the current import with `import {A, B} from 'module';`.

But I thought that was a lot of work for very minimal gain.

**Comment by mhartington** [comment]
Hey! Sorry for dropping the ball on this and the other PRs. I've been on vacation 😄 

Will look into next week

**Comment by pyrho** [comment]
No worries man, life happens :)

**Comment by mhartington** [comment]
So this doesn't seem to work as I would expect. In this example, it cant find `NavParams`, but it's definitely there. I think it has to do with how the candidates are being returned in `getImportCandidates`


auto-import


Here's the nav-to results.
https://gist.github.com/mhartington/dfc2e6682706a69419da002918ada85b

**Comment by pyrho** [comment]
I think I've pinpointed the issue. On it.

**Comment by mhartington** [comment]
Sure thing. I've added you as a collaborator since you've provided a lot of high quality PRs. 

Some general rules can be found here 
http://openopensource.org

But the TLDR:

1) Features get done as PRs
2) Features must be discussed first in an issue.
3) No pushes to master.

**Comment by pyrho** [comment]
Cool thank you (:

I've pushed a fix. I also added a very bare unit test file. It would be nice if we had a unit and functional tests for this plugin. I looked into a few options, I will open an issue to begin a discussion.

**Comment by pyrho** [comment]
Well it turns out your import case is a bit more complex that I expected.
I need to find a way to understand that the user is trying to import from a declaration file, and in that case find out what the name of the module is to import that.

Im going to add breaking tests for this case (there is also the case for trying to import `writeFile` from the `fs` node module for example, where it is slightly different).

I will update asap.

**Comment by pyrho** [comment]
Hey @mhartington I think I fixed the issue you had, I must admit the first iteration was a bit half-assed... sorry.
I also added more tests (including your test case).

I know a discussion is opened on https://github.com/mhartington/nvim-typescript/issues/60 regarding the testing strategy, but I took the liberty of starting a stub in this PR as it was helpful in fixing the feature. I'm not that much of a python guy, so I'm not really sure if my unit testing is very pythonic..

Thanks.

**Comment by mhartington** [comment]
To be honest,  python is not my main language, JS/TS are. So the unit testing bits are things we can work out over time. I'll comment on the issue with some thoughts.

**Comment by mhartington** [comment]
Made some mods, mostly to just add this functionality to utils.py, instead of making a new file. Thanks!

**Pull request closed without merging**
